# Generated by Django 6.1 on 2026-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True, verbose_name='Dirección IP')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos Fallidos')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta')),
                ('stage', models.PositiveSmallIntegerField(default=0, verbose_name='Fase de Bloqueo')),
                ('post_block_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos Post-Bloqueo')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, verbose_name='Último Intento')),
            ],
            options={
                'verbose_name': 'Control de Intentos de Login',
                'verbose_name_plural': 'Controles de Intentos de Login',
            },
        ),
    ]
