# Generated by Django 6.1 on 2026-09-17 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único (UUID)'),
        ),
    ]
